# See https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
logging:
  level:
    ROOT: INFO
server:
  #port: 8080
  http2:
    enabled: true
  jetty:
    max-http-post-size: 32767 # Max per ILP ASN.1
spring:
  profiles:
    # see https://stackoverflow.com/questions/37700352
    active: ${spring.profiles.active}
  output:
    ansi:
      enabled: ALWAYS
  http:
    # MULTIPART (MultipartProperties)
    multipart:
      enabled: false
      max-file-size: 32KB
      max-request-size: 32KB
  # Database Settings
  datasource:
    url: jdbc:h2:mem:example-app;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  servlet:
    session:
      persistent: false # Whether to persist session data between restarts.
      timeout: 0 # Session timeout. If a duration suffix is not specified, seconds will be used.
      tracking-modes: SSL # Session tracking modes.
  session:
    store-type: NONE

###
#   H2 Settings
###
h2:
  console:
    enabled: false
    path: /console
    settings:
      trace: false
      web-allow-others: false

ilpv4:
  connector:
    keystore:
      platform: jks
    btp.enabled: false
    jwtTokenIssuer: https://CHANGEME.example.com
    enabledProtocols:
      blastEnabled: true
      pingProtocolEnabled: true
      peerConfigEnabled: true
      peerRoutingEnabled: true
    ## ILP address of the connector.
    ## This property can be omitted if an account with relation=parent is configured under accounts.
    nodeIlpAddress: test1.connie
    # Global Routing Settings for this connector.
    globalRoutingSettings:
      # Seed used for generating routing table auth values.
      routingSecret: DocIHaveToTellYouSomethingAboutY