# See https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
logging:
  config: classpath:logback-spring.xml
  level:
    ROOT: INFO
    com: INFO
    org.springframework.boot: INFO
    org.springframework.web: INFO
    org.hibernate: INFO
    org.hibernate.SQL: INFO
    org.hibernate.engine: WARN

# By default, all endpoints except for shutdown are enabled.
# https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-features.html#production-ready-endpoints-enabling-endpoints
management:
  endpoints:
    enabled-by-default: false
    health:
      enabled: true
    info:
      enabled: true
    web:
      base-path: "/manage"

server:
  port: 8080
  http2:
    enabled: true
  jetty:
    max-form-post-size: 32767 # Max per ILP ASN.1
spring:
  profiles:
    include: extensions
  cache:
    redis:
      time-to-live: 86400
  output:
    ansi:
      enabled: ALWAYS
  http:
    log-request-details: false
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: false
        format_sql: false
  liquibase:
    enabled: false
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  servlet:
    multipart:
      enabled: false
      max-file-size: 32KB
      max-request-size: 32KB
    session:
      persistent: false # Whether to persist session data between restarts.
      timeout: 0 # Session timeout. If a duration suffix is not specified, seconds will be used.
      tracking-modes: SSL # Session tracking modes.
  session:
    store-type: NONE
  cloud:
    # disabled by default. enabled via the gcp profile
    gcp:
      pubsub:
        enabled: false

interledger:
  connector:
    # ILP address of the connector (can be omitted if an account with relation=parent is configured under accounts).
    # nodeIlpAddress: test.connie
    # adminPassword: password
    # Global Routing Settings for this connector.
    globalRoutingSettings:
      # An ILP address segment that will be used to address any local accounts in the Connector. For example, if an
      # account exists with id of `alice`, then anyone wanting to send packets to alice in the Connector would use the
      # ILP address `{operatorAddress}.accounts.alice`. Typically this will be used in IL-DCP, but will also be used to
      # make routing decisions for any local accounts that might connect to the Connector. For example,
      # `g.connector.accounts.alice.bob` would route to `alice`.
      localAccountsAddressSegment: accounts
      # routingSecret: enc:JKS:crypto.p12:secret0:1:aes_gcm:AAAADKZPmASojt1iayb2bPy4D-Toq7TGLTN95HzCQAeJtz0=
    keys:
      secret0:
        alias: secret0
        version: 1
      accountSettings:
        alias: secret0
        version: 1
    enabledFeatures:
      rateLimitingEnabled: false
      localSpspFulfillmentEnabled: false
      require32ByteSharedSecrets: true
    enabledProtocols:
      ilpOverHttpEnabled: true
      pingProtocolEnabled: true
      peerRoutingEnabled: true
      ildcpEnabled: true
    # settlementEngines:
      # connectionDefaults:
      # Default connect timeout (in milliseconds).
      # connectTimeoutMillis: 10000
      # Applied when connecting a TCP socket to the target host. A value of 0 means no timeout, otherwise values must
      # be between 1 and {@link Integer#MAX_VALUE} when converted to milliseconds.  If unspecified, defaults to 10.
      # This is applied to both the TCP socket and for individual read IO operations. A value of 0 means no timeout,
      # otherwise values must be between 1 and {@link Integer#MAX_VALUE} when converted to milliseconds.  If
      # unspecified, defaults to 10000.
      # readTimeoutMillis: 10000
      # Applied to individual write IO operations. A value of 0 means no timeout, otherwise values must be between 1
      # and {@link Integer#MAX_VALUE} when converted to milliseconds. If unspecified, defaults to 10.
      # writeTimeoutMillis: 30000
      # maxIdleConnections: 5
      # keepAliveMinutes: 5
    # ilpOverHttp:
      # connectionDefaults:
      # Applied when connecting a TCP socket to the target host. A value of 0 means no timeout, otherwise values must
      # be between 1 and {@link Integer#MAX_VALUE} when converted to milliseconds.  If unspecified, defaults to 10.
      # connectTimeoutMillis: 10000
      # This is applied to both the TCP socket and for individual read IO operations. A value of 0 means no timeout,
      # otherwise values must be between 1 and {@link Integer#MAX_VALUE} when converted to milliseconds.  If
      # unspecified, defaults to 10.
      # readTimeoutMillis: 60000
      # Applied to individual write IO operations. A value of 0 means no timeout, otherwise values must be between 1
      # and {@link Integer#MAX_VALUE} when converted to milliseconds. If unspecified, defaults to 10.
      # writeTimeoutMillis: 60000
      # maxIdleConnections: 5
      # keepAliveMinutes: 5
