spring:
  # Database Settings
  datasource:
    url: jdbc:postgresql://localhost:5432/connector
    platform: postgresql
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: none

interledger:
  connector:
    enabledFeatures:
      paymentTransactionMode: in-postgres