# See https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#common-application-properties
logging:
  level:
    ROOT: INFO

server:
  port: 8080
  http2:
    enabled: true
  jetty:
    max-http-post-size: 32767
management:
  endpoints:
    web:
      exposure:
        include: "*"
#  endpoint:
#    refresh:
#      enabled: true

spring:
  output:
    ansi:
      enabled: ALWAYS
  http:
    # MULTIPART (MultipartProperties)
    multipart:
      enabled: false
      max-file-size: 32KB
      max-request-size: 32KB
  resources:
    add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true
  # Database Settings
  datasource:
    url: jdbc:h2:mem:example-app;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: false
        format_sql: false

###
#   H2 Settings
###
h2:
  console:
    enabled: true
    path: /console
    settings:
      trace: false
      web-allow-others: false

interledger:
  connector:
    # For dev purposes this is fine, but not for real use-cases. Encrypt this value instead.
    adminPassword: password
    keystore:
      jks:
        enabled: false
        filename: crypto/crypto.p12
        # For dev purposes this is fine, but not for real use-cases. Encrypt this value instead.
        password: password
        secret0_alias: secret0
        # For dev purposes this is fine, but not for real use-cases. Encrypt this value instead.
        secret0_password: password
    enabledProtocols:
      blastEnabled: true
      pingProtocolEnabled: true
      peerConfigEnabled: true
      peerRoutingEnabled: true
    ## ILP address of the connector.
    ## This property can be omitted if an account with relation=parent is configured under accounts.
    nodeIlpAddress: test.alice
    # Global Routing Settings for this connector.
    globalRoutingSettings:
      # A simulated routing secret, which is a seed used for generating routing table auth values.
      # Represents the plaintext value of `shh`, encrypted.
      routingSecret: enc:JKS:crypto.p12:secret0:1:aes_gcm:AAAADKZPmASojt1iayb2bPy4D-Toq7TGLTN95HzCQAeJtz0=
