# Used for pure development purposes. All accounts are simulated using the Loopback Link.
# See https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#common-application-properties
spring:
  profiles:
    include: h2, management, jks, local-spsp-fulfillment

interledger:
  connector:
    ## ILP address of the connector.
    nodeIlpAddress: test1.connie
    require32ByteSharedSecrets: false
    globalPrefix: test
    adminPassword: password
    globalRoutingSettings:
      routingSecret: enc:JKS:crypto.p12:secret0:1:aes_gcm:AAAADKZPmASojt1iayb2bPy4D-Toq7TGLTN95HzCQAeJtz0=
